# See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
types:
  - add
  - feat
  - update
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
