nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@algolia/autocomplete-preset-algolia@*":
    peerDependenciesMeta:
      "@algolia/client-search":
        optional: true
  "@docusaurus/theme-common@*":
    peerDependenciesMeta:
      prism-react-renderer:
        optional: true
  "@docusaurus/utils@*":
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
      webpack:
        optional: true
  "@easyops-cn/docusaurus-search-local@*":
    peerDependenciesMeta:
      "@docusaurus/theme-common":
        optional: true
  fork-ts-checker-webpack-plugin@*:
    peerDependenciesMeta:
      typescript:
        optional: true
      webpack:
        optional: true
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

yarnPath: .yarn/releases/yarn-3.6.2.cjs
